/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

;


/**
 *
 * @author Briceyda Angeles
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_fondo = new javax.swing.JPanel();
        jmb_barra_menu_paneles = new javax.swing.JMenuBar();
        jme_menu_paneles = new javax.swing.JMenu();
        jmi_mayor3_numeros = new javax.swing.JMenuItem();
        jmi_operaciones = new javax.swing.JMenuItem();
        jmi_ascendente = new javax.swing.JMenuItem();
        jmi_editor_texto = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jpn_fondo.setBackground(new java.awt.Color(255, 255, 255));
        jpn_fondo.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpn_fondoLayout = new javax.swing.GroupLayout(jpn_fondo);
        jpn_fondo.setLayout(jpn_fondoLayout);
        jpn_fondoLayout.setHorizontalGroup(
            jpn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        jpn_fondoLayout.setVerticalGroup(
            jpn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        jme_menu_paneles.setText("Remedial");

        jmi_mayor3_numeros.setText("Mayor de 3 Números");
        jme_menu_paneles.add(jmi_mayor3_numeros);

        jmi_operaciones.setText("Operaciones");
        jme_menu_paneles.add(jmi_operaciones);

        jmi_ascendente.setText("Ascendente");
        jme_menu_paneles.add(jmi_ascendente);

        jmi_editor_texto.setText("Editor de Texto");
        jme_menu_paneles.add(jmi_editor_texto);

        jmi_salir.setText("Salir");
        jme_menu_paneles.add(jmi_salir);

        jmb_barra_menu_paneles.add(jme_menu_paneles);

        setJMenuBar(jmb_barra_menu_paneles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jpn_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jmb_barra_menu_paneles;
    public javax.swing.JMenu jme_menu_paneles;
    public javax.swing.JMenuItem jmi_ascendente;
    public javax.swing.JMenuItem jmi_editor_texto;
    public javax.swing.JMenuItem jmi_mayor3_numeros;
    public javax.swing.JMenuItem jmi_operaciones;
    public javax.swing.JMenuItem jmi_salir;
    public javax.swing.JPanel jpn_fondo;
    // End of variables declaration//GEN-END:variables
}
