/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

;


/**
 *
 * @author Briceyda Angeles
 */
public class ViewEditorTexto extends javax.swing.JPanel {

    /**
     * Creates new form ViewEditorTexto
     */
    public ViewEditorTexto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfc_seleccionador_archivos = new javax.swing.JFileChooser();
        jlb_encabezado = new javax.swing.JLabel();
        jsp_area_trabajo = new javax.swing.JScrollPane();
        jta_area_trabajo = new javax.swing.JTextArea();
        jbtn_abrir = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 153));

        jlb_encabezado.setBackground(new java.awt.Color(0, 0, 0));
        jlb_encabezado.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jlb_encabezado.setText("Editor de Texto");

        jsp_area_trabajo.setBackground(new java.awt.Color(102, 102, 102));

        jta_area_trabajo.setBackground(new java.awt.Color(255, 204, 204));
        jta_area_trabajo.setColumns(20);
        jta_area_trabajo.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jta_area_trabajo.setForeground(new java.awt.Color(51, 0, 51));
        jta_area_trabajo.setRows(5);
        jsp_area_trabajo.setViewportView(jta_area_trabajo);

        jbtn_abrir.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_abrir.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_abrir.setText("Abrir");

        jbtn_guardar.setBackground(new java.awt.Color(255, 153, 255));
        jbtn_guardar.setFont(new java.awt.Font("PakType Naskh Basic", 1, 14)); // NOI18N
        jbtn_guardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsp_area_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addComponent(jlb_encabezado))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jlb_encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsp_area_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_abrir;
    public javax.swing.JButton jbtn_guardar;
    private javax.swing.JFileChooser jfc_seleccionador_archivos;
    public javax.swing.JLabel jlb_encabezado;
    public javax.swing.JScrollPane jsp_area_trabajo;
    public javax.swing.JTextArea jta_area_trabajo;
    // End of variables declaration//GEN-END:variables
}
